{% set name = "tableauserverclient" %}
{% set version = "0.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 30813a57ce312c46e0993c2f3fa8d00b41fffe00673133b5b28c0bd4720c6e94

build:
  number: 0
  # requests is for py>=38
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - pytest-runner
    - versioneer >=0.29
    - wheel
  host:
    - python
    - pip
    - wheel
  run:
    - python
    - defusedxml >=0.7.1
    - packaging >=23.1
    - requests >=2.31
    - urllib3 2.0.7

test:
  imports:
    - tableauserverclient
    - tableauserverclient.models
    - tableauserverclient.server
    - tableauserverclient.server.endpoint
  requires:
    - pip
    - black
    - mock
    - mypy
    - pytest-subtests
    - pytest >=7.0
    # - requests-mock >=1.0,<2.0
  commands:
    - pip check

about:
  home: https://github.com/tableau/server-client-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python library for the Tableau Server REST API

  description: |
    Use the Tableau Server Client (TSC) library to increase your productivity
    as you interact with the Tableau Server REST API. With the TSC library you
    can do almost everything that you can do with the REST API, including
    publish workbooks and data sources, create users and groups, and query
    projects, sites, and more.
  doc_url: https://tableau.github.io/server-client-python/docs/
  dev_url: https://github.com/tableau/server-client-python

extra:
  recipe-maintainers:
    - patlougheed
