travis:
  secure:
    BINSTAR_TOKEN: TaS98Y17PyYAZ64/XECGW1AgP1FIVdxpGSlrd09p62us4h1kcjltZ7/av1OojKR9vk33Vzc8fXEqmMqCl+YkrDiSsU6D3IZ3N40I6A5N3yTm1aRYVxBLq2abptte2KVDojCvEa8bgWdH0s0JVqiZd2Mp0mTMIveCK1vhhuZiHHBUVsVlbcq0FmAbun8ybB4buKnXEmPwXdKHXqJFCeIDy5fSDkh/c08AQ2oTxoxFmtKFtfJqF/MxdZFKYmXT65qxyC/uWAx06S/zn1NGnOAiJLLdl/mGCvvflvRUz5HLeIaL5LATtyBrcIhKooS5xH53oaimdGW9YALLUzbOHQ9KNdrRQHPXU5dUGjTuI5pH1TREeUkMWD375vxarmpx4C/nW3R/6pz1wWkXH6Sdf+TLXC6/BEn36TmKM0ee4JOg8b7SaUMI1XHKfpiIHOB+8rQ86w+ybyYJyVU0AJezdfELnt9ASkbkw+V/O5u6EvkrpRPbsA/MMfsYiuj+PIEWxIvs7YDb2j2rVcD0Sw0xkUdtUPQ48mNgGiFfI34gUbUQDMxg4wJT7ENiyhdy9f5WeRNhrjbo4Ofw4HbfhAOXKdbuWdFfSey7m14xrY0/2cY7tcxiQROvca6sd1m+Qphm8z1MG7NYut2ETmbu2BM/n2DzoYosLLc0PC1ZJy3MDGzu/nE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
